---
title: "carsToSQL"
author: "Pablo Martin Sanchez"
date: "2024-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Funcion para libreiras, eval=TRUE, echo=TRUE, results='hide'}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if(length(new.pkg))
    install.packages(new.pkg, dependecies=TRUE)
  sapply(pkg, require, character.only = TRUE)
}

```

```{r}
libreries <- c("RPostgres", "RODBC", "odbc", "DBI", "dplyr", "readr",
               "rlang", "stringr","tidyverse","ggplot2", "doParallel", "foreach"
               ,"stringi", "utf8","tm")
ipak(libreries)
```


## R Markdown

Quitar los coches que no tienen marca o modelo

```{r}
dataCar_BackUp <- dataCar
dataCar <- dataCar[!(grepl("\\s*-\\s*", dataCar$make) | grepl("\\s*-\\s*", dataCar$model)), ]
```

## Probar base de datos online.

```{r pgConn_Covid, eval=TRUE, echo=TRUE, cache=TRUE}
pgConn <- dbConnect(RPostgres::Postgres(), dbname = 'TFM_Coches',
                    host = '127.0.0.1',
                    port = 5432, # or any other specified by your own)
                    user = 'postgres',
                    password = "9170")
dbListTables(pgConn)
```


```{r carConn, eval=TRUE, echo=TRUE, cache=TRUE}
carConn <- dbConnect(RPostgres::Postgres(), dbname = 'datacar',
                    host = 'datacar-13919.8nj.gcp-europe-west1.cockroachlabs.cloud',
                    port = 26257, # or any other specified by your own)
                    user = 'pabmarsan2_gmail_com',
                    password = "NqYqMdT1ecYpn6MuBQUB8w")
dbListTables(carConn)
```

## Crear tabla Marcas

```{sql connection=pgConn, eval=FALSE}
DO $$
BEGIN
    -- Verificar si la tabla existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'marcas') THEN
        -- Si la tabla no existe, crearla
        CREATE TABLE marcas (
            makeid SERIAL PRIMARY KEY, 
            make VARCHAR(50) UNIQUE
        );
        -- Imprimir un mensaje de confirmación
        RAISE NOTICE 'La tabla marcas ha sido creada correctamente.';
    ELSE
        -- Si la tabla ya existe, imprimir un mensaje de aviso
        RAISE NOTICE 'La tabla marcas ya existe.';
    END IF;
END $$;
```
```{sql connection=carConn, eval=FALSE}
        CREATE TABLE versiones (
            versionid SERIAL PRIMARY KEY, 
            version VARCHAR(255) UNIQUE
        );
```
```{r marcas_unicos, eval=TRUE, echo=TRUE, cache=TRUE}
dataCar$make <- toupper(dataCar$make)
marcas_unicas <- unique(dataCar$make) 
marcas_unicas <- aggregate(makeId ~ make, data = dataCar, FUN = function(x) unique(x))
marcas_unicas
 
# Recorrer el dataframe como una matriz
for (i in 1:nrow(marcas_unicas)) {
  if (is.list(marcas_unicas$makeId[i])) {  # Comprueba si es una lista
    marcas_unicas$makeId[i] <- marcas_unicas$makeId[i][[1]]  # Obtiene el primer elemento de la lista
  }
}
marcas_unicas <- marcas_unicas[!str_detect(marcas_unicas$makeId, "\\s*-\\s*"), ]

n <- length(marcas_unicas$makeid)
nuevos_ids <- seq(1, n)
# Asignar los nuevos IDs al dataframe
marcas_unicas$makeid <- nuevos_ids
```


```{r writeMarcas, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(marcas_unicas)
nuevos_nombres <- tolower(nombres_columnas)
colnames(marcas_unicas) <- nuevos_nombres

marcas_unicas$makeid <- as.numeric(marcas_unicas$makeid)

dbWriteTable(pgConn, name = "marcas",
             value = marcas_unicas,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)
```

## Crear tabla modelos

```{sql connection=pgConn, eval=FALSE}
DO $$
BEGIN
    -- Verificar si la tabla existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'modelos') THEN
        -- Si la tabla no existe, crearla
        CREATE TABLE modelos (
            modelid SERIAL PRIMARY KEY, 
            model VARCHAR(255) UNIQUE
        );
        -- Imprimir un mensaje de confirmación
        RAISE NOTICE 'La tabla modelos ha sido creada correctamente.';
    ELSE
        -- Si la tabla ya existe, imprimir un mensaje de aviso
        RAISE NOTICE 'La tabla modelos ya existe.';
    END IF;
END $$;
```

```{r model_unicos, eval=TRUE, echo=TRUE, cache=TRUE}
modelos_unicas <- unique(dataCar$model) 
modelos_unicas <- aggregate(modelId ~ model, data = dataCar, FUN = function(x) unique(x))
modelos_unicas

n <- length(modelos_unicas$modelid)
nuevos_ids <- seq(1, n)
# Asignar los nuevos IDs al dataframe
modelos_unicas$modelid <- nuevos_ids

modelos_unicas
```

```{r writeModelos, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(modelos_unicas)
nuevos_nombres <- tolower(nombres_columnas)
colnames(modelos_unicas) <- nuevos_nombres
modelos_unicas$modelid <- as.numeric(modelos_unicas$modelid)


dbWriteTable(pgConn, name = "modelos",
             value = modelos_unicas,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)
```


## Crear tabla versiones

```{sql connection=pgConn, eval=FALSE}
DO $$
BEGIN
    -- Verificar si la tabla existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'versiones') THEN
        -- Si la tabla no existe, crearla
        CREATE TABLE versiones (
            versionid SERIAL PRIMARY KEY, 
            version VARCHAR(255) UNIQUE
        );
        -- Imprimir un mensaje de confirmación
        RAISE NOTICE 'La tabla versiones ha sido creada correctamente.';
    ELSE
        -- Si la tabla ya existe, imprimir un mensaje de aviso
        RAISE NOTICE 'La tabla versiones ya existe.';
    END IF;
END $$;
```


```{r model_unicos, eval=TRUE, echo=TRUE, cache=TRUE}
versiones_unicas <- unique(dataCar$version) 
versiones_unicas <- aggregate(versionid ~ version, data = dataCar, FUN = function(x) unique(x))

n <- length(versiones_unicas$versionid)
nuevos_ids <- seq(1, n)
# Asignar los nuevos IDs al dataframe
versiones_unicas$versionid <- nuevos_ids
versiones_unicas <- versiones_unicas[-c(1:3), ]
```

```{r writeVersiones, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(versiones_unicas)
nuevos_nombres <- tolower(nombres_columnas)
colnames(versiones_unicas) <- nuevos_nombres
versiones_unicas$versionid <- as.numeric(versiones_unicas$versionid)


dbWriteTable(pgConn, name = "versiones",
             value = versiones_unicas,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)
```

## Crear tablas provincias

```{sql connection=pgConn, eval=FALSE}
DO $$
BEGIN
    -- Verificar si la tabla existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'provincias') THEN
        -- Si la tabla no existe, crearla
        CREATE TABLE provincias (
            provinceid SERIAL PRIMARY KEY, 
            province VARCHAR(255) UNIQUE
        );
        -- Imprimir un mensaje de confirmación
        RAISE NOTICE 'La tabla provincias ha sido creada correctamente.';
    ELSE
        -- Si la tabla ya existe, imprimir un mensaje de aviso
        RAISE NOTICE 'La tabla provincias ya existe.';
    END IF;
END $$;
```

```{r provincias_unicos, eval=TRUE, echo=TRUE, cache=TRUE}
provincias_unicas <- unique(dataCar$province) 
provincias_unicas <- aggregate(provinceid ~ province, data = dataCar, FUN = function(x) unique(x))
provincias_unicas[1, 2] <- 0
```

```{r provincias_unicos_raw, eval=TRUE, echo=TRUE, cache=TRUE}
provincias_unicas <- data.frame(
  province = c(" ", "A Coruna", "Alava", "Albacete", "Alicante", "Almeria", "Asturias", "Avila", "Badajoz", "Baleares","Barcelona", "Burgos", "Caceres", "Cadiz", "Cantabria", "Castellon", "Ciudad Real", "Cordoba", "Cuenca", "Girona", "Granada", "Guadalajara", "Guipuzcoa", "Huelva", "Huesca", "Jaen", "La Rioja", "Las Palmas",
 "Leon", "Lleida", "Lugo", "Madrid", "Malaga", "Murcia", "Navarra", "Orense", "Palencia", "Pontevedra",
"Salamanca", "Segovia", "Sevilla", "Soria", "Sta. C. Tenerife", "Tarragona", "Teruel", "Toledo", "Valencia",
"Valladolid", "Vizcaya", "Zamora", "Zaragoza", "Ceuta", "Melilla"),
  provinceid = c(0, 15, 1, 2, 3, 4, 33, 5, 6, 7, 8, 9, 10, 11, 39, 12, 13, 14, 16, 17,
                 18, 19, 20, 21, 22, 23, 26, 35, 24, 25, 27, 28, 29, 30, 31, 32, 34, 36,
                 37, 40, 41, 42, 38, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52)
)
```


```{r writeProvincias, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(provincias_unicas)
nuevos_nombres <- tolower(nombres_columnas)
colnames(provincias_unicas) <- nuevos_nombres
provincias_unicas$provinceid <- as.numeric(provincias_unicas$provinceid)


dbWriteTable(pgConn, name = "provincias",
             value = provincias_unicas,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)
```

## Crear tabla bodyType

```{r cotejar_bodytype}
dataCar$bodytypeid <- trimws(dataCar$bodytypeid)
body <- unique(dataCar$bodytypeid)
primeros_5_ejemplos <- data.frame()
for (valor in body) {
  print(valor)
  resultados_filtrados <- dataCar[dataCar$bodytypeid == valor, ]
  ejemplos <- resultados_filtrados[, c("title", "bodytypeid")]
  ejemplos <- head(ejemplos, 5)
  primeros_5_ejemplos <- rbind(primeros_5_ejemplos, ejemplos)
}
primeros_5_ejemplos

# Fichas tecnicas de vehiculos 41.384 Todas las ventas coinciden del 1 al 8
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE bodytype (
  body_type_id INTEGER PRIMARY KEY,
  body_type VARCHAR(255) UNIQUE
  );
```


```{r writeVersiones, eval=FALSE, echo=TRUE, cache=TRUE}
bodyType_df <- data.frame(
  body_type_id = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
  body_type = c("turismo", "coupe", "descapotable", "turismo_familiar", "monovolumen", "todoterreno", "pick_up", "furgoneta", "")
)

dbWriteTable(pgConn, name = "bodytype",
             value = bodyType_df,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(bodyType_df)
```


## Crear tabla transmision

```{r cotejar_transmision}
dataCar$bodytypeid <- trimws(dataCar$transmissiontypeid)
body <- unique(dataCar$transmissiontypeid)
primeros_5_ejemplos <- data.frame()
for (valor in body) {
  print(valor)
  resultados_filtrados <- dataCar[dataCar$transmissiontypeid == valor, ]
  ejemplos <- resultados_filtrados[, c("title", "transmissiontypeid")]
  ejemplos <- head(ejemplos, 5)
  primeros_5_ejemplos <- rbind(primeros_5_ejemplos, ejemplos)
}
primeros_5_ejemplos

# Fichas tecnicas de vehiculos 41.384 Todas las ventas coinciden del 1 al 8
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE transmision (
  transmision_type_id INTEGER PRIMARY KEY,
  transmision_type VARCHAR(255) UNIQUE
  );
```


```{r writetransmision, eval=FALSE, echo=TRUE, cache=TRUE}
transmisionType_df <- data.frame(
  transmision_type_id = c(1, 2, 3),
  transmision_type = c("automatica", "manual", "")
)

dbWriteTable(pgConn, name = "transmision",
             value = transmisionType_df,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(transmisionType_df)
```

## Crear tabla combustible

```{r cotejar_fueltype_ventas}
csv$fuelTypeId <- trimws(csv$fuelTypeId)
body <- unique(csv$fuelTypeId)
primeros_5_ejemplos <- data.frame()
for (valor in body) {
  print(valor)
  resultados_filtrados <- csv[csv$fuelTypeId == valor, ]
  ejemplos <- resultados_filtrados[, c("title", "fuelTypeId", "fuelType")]
  ejemplos <- head(ejemplos, 5)
  primeros_5_ejemplos <- rbind(primeros_5_ejemplos, ejemplos)
}
primeros_5_ejemplos

# Fichas tecnicas de vehiculos 41.384 Todas las ventas coinciden del 1 al 8
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE combustible (
  combustible_type_id INTEGER PRIMARY KEY,
  combustible_type VARCHAR(255) UNIQUE
  );
```


```{r writecombustible_df, eval=FALSE, echo=TRUE, cache=TRUE}
combustible_df <- data.frame(
  combustible_type_id = c(1, 2, 3, 4, 5, 6, 7, 8),
  combustible_type = c("diesel", "gasolina", "electrico", "hibrido", "hibrido_enchufable", "gas_licuado_(GLP)", "gas_natural_(CNG)", "")
)

dbWriteTable(pgConn, name = "combustible",
             value = combustible_df,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(combustible_df)
```


## Crear tabla colores

```{r cotejar_colores}
dataCar$vehiclecolorid <- trimws(dataCar$vehiclecolorid)
body <- unique(dataCar$vehiclecolorid)
primeros_5_ejemplos <- data.frame()
for (valor in body) {
  print(valor)
  resultados_filtrados <- dataCar[dataCar$vehiclecolorid == valor, ]
  ejemplos <- resultados_filtrados[, c("title", "vehiclecolor", "vehiclecolorid")]
  ejemplos <- head(ejemplos, 5)
  primeros_5_ejemplos <- rbind(primeros_5_ejemplos, ejemplos)
}
primeros_5_ejemplos

# Fichas tecnicas de vehiculos 41.384 Todas las ventas coinciden del 1 al 8
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE colores (
  colores_type_id SERIAL PRIMARY KEY,
  colores_type VARCHAR(255) UNIQUE
  );
```


```{r writecolores_df, eval=FALSE, echo=TRUE, cache=TRUE}
colores_df <- data.frame(
  colores_type_id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13),
  colores_type = c("Amarillo", "Azul", "Beige", "Blanco", "Granate", "Gris", "Marron", "Naranja", "Negro", "Rojo", "Rosa", "Verde", "")
)

dbWriteTable(pgConn, name = "colores",
             value = colores_df,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(colores_df)
```


## Crear tabla fichas tecnicas

```{r sql_create_table, eval=FALSE, echo=TRUE, cache=TRUE}
col_names <- colnames(car_SQL)

# Generar la consulta SQL dinámica para crear la tabla
create_table_query <- paste("CREATE TABLE fichas_tecnicas (",
                            paste(col_names, "VARCHAR(255)", collapse = ", "),
                            ");", sep = "")
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE fichas_tecnicas (
  id INTEGER PRIMARY KEY,
  photos VARCHAR(255),
  vehicleyear VARCHAR(255), 
  vehiclecolorid INTEGER REFERENCES colores(colores_type_id) , 
  makeid INTEGER REFERENCES marcas(makeid), 
  modelid INTEGER REFERENCES modelos(modelid), 
  versionid INTEGER REFERENCES versiones(versionid),
  bodytypeid INTEGER REFERENCES bodytype(body_type_id), 
  doors VARCHAR(255), 
  transmissiontypeid INTEGER REFERENCES transmision(transmision_type_id), 
  fueltypeid INTEGER REFERENCES combustible(combustible_type_id), 
  seatingcapacity VARCHAR(255),
  horsepower VARCHAR(255),
  dimensionsinmillimeterswidth VARCHAR(255), 
  dimensionsinmillimetersheight VARCHAR(255), 
  dimensionsinmillimeterslength VARCHAR(255), 
  trunkcapacityinliters VARCHAR(255), 
  weight VARCHAR(255), 
  tankcapacityinliters VARCHAR(255), 
  consumptionurban VARCHAR(255), 
  consumptionmixed VARCHAR(255), 
  consumptionextraurban VARCHAR(255), 
  maxspeed VARCHAR(255), 
  acceleration VARCHAR(255), 
  manufacturerprice VARCHAR(255), 
  co2emissionsgramsperkm VARCHAR(255), 
  batteryvoltage VARCHAR(255), 
  batterykwh VARCHAR(255), 
  chargingtime VARCHAR(255), 
  chargingtimefast VARCHAR(255)
);

```


```{r eval=TRUE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(dataCar)
nuevos_nombres <- tolower(nombres_columnas)
colnames(dataCar) <- nuevos_nombres

car_SQL <- data.frame()
for (i in 1:nrow(dataCar)) {
  if (toupper(dataCar[i, "make"]) %in% marcas_unicas$make) {
    if (dataCar[i, "model"] %in% modelos_unicas$model) {
      if (dataCar[i, "version"] %in% versiones_unicas$version) {
        print(i)
        dataCar[i, "makeid"] <-
          marcas_unicas$makeid[marcas_unicas$make == toupper(dataCar[i, "make"])]
        dataCar[i, "modelid"] <-
          modelos_unicas$modelid[modelos_unicas$model == dataCar[i, "model"]]
        dataCar[i, "versionid"] <-
         versiones_unicas$versionid[versiones_unicas$version == dataCar[i, "version"]]
        car_SQL <- rbind(car_SQL, dataCar[i, ])
      }
    }
  }
}
```

```{r eval=TRUE, echo=TRUE, cache=TRUE}
for (i in 1:nrow(car_SQL)) {
  if (!(car_SQL[i, "bodytypeid"] %in% bodyType_df$body_type_id)) {
    print(i)
    car_SQL[i, "bodytypeid"] <- 9
  }
  if (!(car_SQL[i, "transmissiontypeid"] %in% transmisionType_df$transmision_type_id)) {
    print(i)
    car_SQL[i, "transmissiontypeid"] <- 3
  }
  if (!(car_SQL[i, "fueltypeid"] %in% combustible_df$combustible_type_id)) {
    print(i)
    car_SQL[i, "fueltypeid"] <- 8
  }
  if (!(car_SQL[i, "vehiclecolorid"] %in% colores_df$colores_type_id)) {
    print(i)
    car_SQL[i, "vehiclecolorid"] <- 13
  }
}

table(car_SQL$bodytypeid)
table(car_SQL$transmissiontypeid)
table(car_SQL$fueltypeid)
table(car_SQL$vehiclecolorid)
```


```{r writeFichas, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(car_SQL)
nuevos_nombres <- tolower(nombres_columnas)
colnames(car_SQL) <- nuevos_nombres
colnames(car_SQL)[colnames(car_SQL) == "end"] <- "end_"
#car_SQL <- car_SQL[, -ncol(car_SQL)]
toWrite <- subset(car_SQL, select = -c(title, url, price, vehiclekm,
                                       vehiclecolor, vehicleiscertified, 
                                       certificatedprogramid, hasvehiclehistory,
                                       make, model, version, uniquevehicleid,
                                       power, professionalsellerid, externaladid,
                                       istradable, province, provinceid, year,
                                       numberofdoors, numberofseats, start,
                                       end_))

dbWriteTable(pgConn, name = "fichas_tecnicas",
             value = toWrite,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(toWrite)
```

## Crear tabla ventas

```{r sql_create_table, eval=FALSE, echo=TRUE, cache=TRUE}
col_names <- colnames(csv_SQL)

# Generar la consulta SQL dinámica para crear la tabla
create_table_query <- paste("CREATE TABLE ventas (",
                            paste(col_names, "VARCHAR(255)", collapse = ", "),
                            ");", sep = "")
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE ventas (
  creationdate VARCHAR(255),
  url VARCHAR(255),
  km VARCHAR(255),
  provinceid INTEGER REFERENCES provincias(provinceid),
  environmentallabel VARCHAR(255),
  price_amount VARCHAR(255),
  url_true VARCHAR(255),
  ficha_id INTEGER REFERENCES fichas_tecnicas(id)
  );
```


```{r eval=TRUE, echo=TRUE, cache=TRUE}
for (i in 1:nrow(csv)) {
  title_match <- car_SQL$id[car_SQL$title == csv[i, "title"]]
  #print(title_match)
   if (length(title_match) > 0) {
     if(title_match[1] %in% dataCar$id) {
       csv[i, "ficha_id"] <- title_match[1]  # Seleccionar solo el primer valor
     }else{
      csv[i, "ficha_id"] <- title_match[2]
    }
  } else {
    csv[i, "ficha_id"] <- "0"
  }
}
```

```{r eval=TRUE, echo=TRUE, cache=TRUE}
ventas <- 0
for (i in 1:nrow(csv)) {
  if (csv[i, "ficha_id"] > 0) {
    ventas <- ventas + 1  # Seleccionar solo el primer valor
  }
}
ventas
csv_SQL <- subset(csv, ficha_id != 0)
```

```{r writeVentas, eval=FALSE, echo=TRUE, cache=TRUE}
nombres_columnas <- colnames(csv_SQL)
nuevos_nombres <- tolower(nombres_columnas)
colnames(csv_SQL) <- nuevos_nombres

toWrite <- subset(csv_SQL, select = -c(brand, model, version, title,
                                       year, cubiccapacity,
                                       makeid, modelid, fueltypeid, 
                                       fueltype, bodytypeid, drivenwheelsid,
                                       transmissiontypeid, warranty_months,
                                       offertype_id, offertype_literal, 
                                       pack_legacyid, pack_type, url, provinceid))



toWrite$mainprovince <- iconv(toWrite$mainprovince, "latin1", "UTF-8")
toWrite$mainprovince <- gsub("A Coruña", "A Coruna", toWrite$mainprovince, fixed = TRUE)
toWrite$mainprovince <- gsub("Guipúzcoa", "Guipuzcoa", toWrite$mainprovince, fixed = TRUE)
toWrite$mainprovince <- trimws(toWrite$mainprovince)

for (i in 1:nrow(toWrite)) {
  if ((toupper(toWrite[i, "mainprovince"]) %in% toupper(provincias_unicas$province))) {
    #print(paste(toWrite[i, "mainprovince"]))
    toWrite[i, "mainprovince"] <-
      provincias_unicas$provinceid[(toupper(toWrite[i, "mainprovince"]) == toupper(provincias_unicas$province))]
  } else{
    print(paste("No coincide: ", toWrite[i, "creationdate"], "  -  ", toWrite[i, "mainprovince"]))
    toWrite[i, "mainprovince"] <- 0
  }
}

names(toWrite)[names(toWrite) == "url_true"] <- "url"
names(toWrite)[names(toWrite) == "mainprovince"] <- "provinceid"
toWrite$provinceid <- iconv(toWrite$provinceid, "UTF-8", "latin1")
toWrite$url <- iconv(toWrite$url, "UTF-8", "latin1")
dbWriteTable(pgConn, name = "ventas",
             value = toWrite,
             append=TRUE,
             field.types=NULL,
             batch_rows = 5000)

rm(toWrite)

```



## asdad

```{r}
manufactured <- 0
for (i in 1:nrow(dataCar)) {
  if (dataCar[i, "manufacturerprice"] > 0) {
    manufactured <- manufactured + 1  # Seleccionar solo el primer valor
  }
}
manufactured

#31840 fichas tecnicas con el precio de original

```


```{r}
query <- "select  v.price_amount, ft.manufacturerprice, v.km, ft.vehicleyear, 
	v.environmentallabel, p.province, 
	ft.horsepower, ft.maxspeed, ft.acceleration, 
	com.combustible_type, b.body_type, t.transmision_type,
	ft.doors, ft.seatingcapacity, c.colores_type,   
	ft.dimensionsinmillimeterswidth, ft.dimensionsinmillimetersheight,
	ft.dimensionsinmillimeterslength, ft.weight, 
	ft.tankcapacityinliters, ft.trunkcapacityinliters, 
	ft.consumptionurban, ft.consumptionmixed, ft.consumptionextraurban,  
	ft.co2emissionsgramsperkm, ft.batteryvoltage, ft.batterykwh,
	ft.chargingtime, ft.chargingtimefast 
	from ventas v 
	inner join provincias p on v.provinceid = p.provinceid
	inner join fichas_tecnicas ft on v.ficha_id = ft.id
	inner join colores c on ft.vehiclecolorid = c.colores_type_id
	inner join transmision t on ft.transmissiontypeid = t.transmision_type_id 
	inner join bodytype b on ft.bodytypeid = b.body_type_id
	inner join combustible com on ft.fueltypeid = com.combustible_type_id"
ventas_df <- dbGetQuery(pgConn, query)

# Mostrar los primeros registros del dataframe
head(ventas_df)
write.csv(ventas_df, "ventas_dataframe.csv")
```

```{sql connection=pgConn, message=FALSE, warning=FALSE, eval=FALSE}
CREATE TABLE ventas (
  creationdate VARCHAR(255),
  url VARCHAR(255),
  km VARCHAR(255),
  provinceid INTEGER REFERENCES provincias(provinceid),
  environmentallabel VARCHAR(255),
  price_amount VARCHAR(255),
  url_true VARCHAR(255),
  ficha_id INTEGER REFERENCES fichas_tecnicas(id)
  );
```




